In [2]:
#Importing libraries
import numpy as np

In [3]:
#reading data file
filename = 'abc.txt'
data = np.loadtxt(filename,delimiter='\t')

In [4]:
#Separating X and Y columns
x0 = data[0:,0]
y0 = data[0:,1]

In [10]:
#Table
print('x\ty\txy\tx^2\tx^2*y\tx^3\tx^4')

#College table
for i in range (0,x0.shape[0]):
    print(x0[i],'\t',y0[i],'\t',x0[i]*y0[i],'\t',x0[i]**2,'\t',x0[i]**2*y0[i],'\t',x0[i]**3,'\t',x0[i]**4)

#Actual calculations
x = np.sum(x0)
y = np.sum(y0)
xy = np.sum(x0*y0)
xr2 = np.sum(x0**2)
xr2y = np.sum(x0**2*y0)
xr3 = np.sum(x0**3)
xr4 = np.sum(x0**4)
n0 = x0.shape[0]

print('\n',x,'\t',y,'\t',xy,'\t',xr2,'\t',xr2y,'\t',xr3,'\t',xr4,'\t',n0)

x	y	xy	x^2	x^2*y	x^3	x^4
-3.0 	 12.0 	 -36.0 	 9.0 	 108.0 	 -27.0 	 81.0
-2.0 	 4.0 	 -8.0 	 4.0 	 16.0 	 -8.0 	 16.0
-1.0 	 1.0 	 -1.0 	 1.0 	 1.0 	 -1.0 	 1.0
0.0 	 2.0 	 0.0 	 0.0 	 0.0 	 0.0 	 0.0
1.0 	 7.0 	 7.0 	 1.0 	 7.0 	 1.0 	 1.0
2.0 	 15.0 	 30.0 	 4.0 	 60.0 	 8.0 	 16.0
3.0 	 30.0 	 90.0 	 9.0 	 270.0 	 27.0 	 81.0

 0.0 	 71.0 	 82.0 	 28.0 	 462.0 	 0.0 	 196.0 	 7


In [13]:
#Guass elimination
n = 3

# Making numpy array of n x n+1 size and initializing 
# to zero for storing augmented matrix
a = np.zeros((n,n+1))

# Making numpy array of n size and initializing 
# to zero for storing solution vector
root = np.zeros(n)

a[0][0]=xr2
a[0][1]=x
a[0][2]=n0
a[0][3]=y
a[1][0]=xr3
a[1][1]=xr2
a[1][2]=x
a[1][3]=xy
a[2][0]=xr4
a[2][1]=xr3
a[2][2]=xr2
a[2][3]=xr2y

print(a)

# Applying Gauss Elimination
for i in range(n):
    if a[i][i] == 0.0:
        print('Divide by zero detected!')
        break

    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]

        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]

# Back Substitution
root[n-1] = a[n-1][n]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    root[i] = a[i][n]

    for j in range(i+1,n):
        root[i] = root[i] - a[i][j]*root[j]

    root[i] = root[i]/a[i][i]

[[ 28.   0.   7.  71.]
 [  0.  28.   0.  82.]
 [196.   0.  28. 462.]]


In [14]:
#results
print('y = (%0.5f) * x^2 +  (%0.5f) * x + (%0.5f)' %(root[0],root[1],root[2]))

y = (2.11905) * x^2 +  (2.92857) * x + (1.66667)
